# talon/server/auth.py
# Client enrollment, lease management, and revocation.
#
# Lifecycle of a client:
#   1. Server generates an enrollment token (out-of-band handoff)
#   2. Client presents the token over Reticulum to request enrollment
#   3. Server validates, creates a client record, issues a lease token
#   4. Client renews the lease every 24 hours automatically
#   5. If the lease expires → soft-lock (client still has data, can re-auth)
#   6. If revoked → hard shred on client, identity burned, group key rotated
#
# This module handles steps 2-6 on the server side.

import os
import time

from talon.crypto.group_key import rotate_group_key
from talon.crypto.lease import generate_lease_token, is_lease_valid, sign_lease


def enroll_client(
    enrollment_token: str, client_identity: str, callsign: str, valid_tokens: dict, server_secret: bytes
) -> dict:
    """Process a client enrollment request.

    Args:
        enrollment_token: The token the client is presenting.
        client_identity: The client's Reticulum identity hash.
        callsign: The callsign the operator wants to use.
        valid_tokens: Dict of {token: metadata} generated by the server.
        server_secret: Server's secret key for signing leases.

    Returns:
        Dict with enrollment result:
        - "success": bool
        - "lease": lease token dict (if successful)
        - "error": error message (if failed)
    """
    # Check the token is valid and hasn't been used
    if enrollment_token not in valid_tokens:
        return {"success": False, "error": "Invalid or expired enrollment token"}

    token_meta = valid_tokens[enrollment_token]
    if token_meta.get("used"):
        return {"success": False, "error": "Enrollment token already used"}

    # Mark token as used so it can't be replayed
    token_meta["used"] = True
    token_meta["used_by"] = callsign
    token_meta["used_at"] = time.time()

    # Generate a lease for the new client
    lease = generate_lease_token()
    signature = sign_lease(lease["token"], server_secret)

    return {
        "success": True,
        "lease": lease,
        "signature": signature,
        "client_identity": client_identity,
        "callsign": callsign,
    }


def generate_enrollment_token() -> str:
    """Generate a one-time enrollment token for a new client.

    This token is given to the operator out-of-band (e.g., in person,
    over a secure channel). It proves they are authorised to join.

    Returns:
        A 32-character hex string (16 random bytes).
    """
    return os.urandom(16).hex()


def renew_lease(client_id: str, current_lease: dict, server_secret: bytes) -> dict:
    """Renew a client's lease token.

    Called when a client's lease is still valid and they request renewal.

    Args:
        client_id: The client's identity hash.
        current_lease: The client's current lease dict.
        server_secret: Server's secret key for signing.

    Returns:
        New lease dict with fresh expiry, or error dict.
    """
    if not is_lease_valid(current_lease):
        return {"success": False, "error": "Current lease is expired — server operator must approve re-authentication"}

    new_lease = generate_lease_token()
    signature = sign_lease(new_lease["token"], server_secret)

    return {
        "success": True,
        "lease": new_lease,
        "signature": signature,
    }


def approve_reauth(client_id: str, server_secret: bytes) -> dict:
    """Server operator manually approves a client whose lease expired.

    This is the soft-lock recovery path. The client still has their data
    but cannot sync until the server operator explicitly allows it.

    Args:
        client_id: The client's identity hash.
        server_secret: Server's secret key for signing.

    Returns:
        New lease dict.
    """
    new_lease = generate_lease_token()
    signature = sign_lease(new_lease["token"], server_secret)

    return {
        "success": True,
        "lease": new_lease,
        "signature": signature,
        "reauth": True,
    }


def revoke_client(client_id: str, reason: str, current_group_key: bytes) -> dict:
    """Revoke a client — hard action.

    What happens on revocation:
    1. Client is added to the deny list (can never reconnect)
    2. Group encryption key is rotated (client can't decrypt new data)
    3. A shred command is queued for the client (if it comes online)
    4. All other clients receive the new group key on next sync

    Args:
        client_id: The client's identity hash.
        reason: Why the client is being revoked (logged in audit).
        current_group_key: The current group encryption key.

    Returns:
        Dict with revocation details and the new group key.
    """
    # Rotate the group key so the revoked client can't decrypt future data
    new_group_key = rotate_group_key()

    return {
        "revoked_client": client_id,
        "reason": reason,
        "new_group_key": new_group_key,
        "shred_queued": True,
        "timestamp": time.time(),
    }
